spring:
  application:
    name: yourmusicserver
    datasource:
      url: jdbc:mysql://localhost:3306/yourmusicdb?useSSL=false&serverTimezone=UTC
      username: youruser
      password: yourpassword

jwt:
  secret-key: ${SECRET_KEY}
  access-token-expire-time: 300     # 5??
  refresh-token-expire-time: 7200   # 2???

server:
  port: 9090

  spring:
    datasource:
      url: jdbc:mysql://localhost:3306/yourmusicdb?useSSL=false&serverTimezone=UTC
      username: youruser
      password: yourpassword
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.MySQLDialect

