spring:
  application:
    name: yourmusicserver

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

jwt:
  secret-key: ${SECRET_KEY}
  access-token-expire-time: 300     # 5? (???)
  refresh-token-expire-time: 7200   # 2?? (???)

server:
  port: 9090

